# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirbnbRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('neighborhood', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('accomodates', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('guestsIncluded', models.IntegerField(default=0)),
                ('cancellationPolicy', models.IntegerField(default=0)),
                ('apartamentType', models.IntegerField(default=0)),
                ('entireApartament', models.BooleanField(default=False)),
                ('typeOfRoom', models.IntegerField(default=0)),
                ('typeOfBed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('AirbnbRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteApp.AirbnbRequest')),
            ],
        ),
    ]
